UIMPROF-78 Upgrade react-redux to v8.
folio-org/ui-myprofile pull request #204
Opened 2023-01-23 02:10 UTC by ryandberger

- Refs https://issues.folio.org/browse/UIMPROF-78.
- Upgrade will be happening across all of Stripes framework and modules that reference react-redux.
- v7 to v8 is a very harmless upgrade and is only considered breaking since they removed a few rarely used functions (which I confirmed we don't use). See https://github.com/reduxjs/react-redux/releases/tag/v8.0.0 for more details.

2023-01-23 11:18 UTC, BogdanDenis requested changes

2023-01-23 11:18 UTC, BogdanDenis commented on package.json
> +    "@folio/stripes": "^8.0.0",
Hey @ryandberger , thanks for the PR! We already upgraded `stripes`, so the only thing left is `react-redux`

2023-01-23 23:04 UTC, zburke requested changes
Please use an available version for stripes-connect minimum value.

2023-01-24 02:25 UTC, zburke approved these changes

2023-01-24 02:28 UTC, merged