Upgrade to react 18 and also leverage jest-config-stripes for all jes…
folio-org/ui-myprofile pull request #206
Opened 2023-08-02 09:11 UTC by Terala-Priyanka

…t and testing-library packages

2023-08-02 20:31 UTC, artem-blazhko approved these changes

2023-08-03 11:20 UTC, Dmitriy-Litvinenko approved these changes

2023-08-04 15:07 UTC, zburke requested changes
Please eliminate the hard-coded timeout added in the test. If you can't find a solution, then ask for help on Slack#stripes, and if you _still_ can't find a solution, then we can stick with the timeout but with some comments explaining the problem, ideally including an explanation of why we think the usual approach of waiting for an element didn't work.

2023-08-07 17:06 UTC, Terala-Priyanka commented on src/settings/ChangePassword/ChangePassword.test.js
> +      await new Promise(resolve => setTimeout(resolve, 1000));
Hey @zburke 
Here is the result of my analysis -

1. In this case submit button will not disappear, rather it gets disabled. 'waitForElementToBeRemoved' doesn't help here.
2. Looks like "PasswordStrength" component disappears after clicking submit button. I tried implementing this, but "waitForElementToBeRemoved" is getting timedout and upon further investigation, I have observed that PasswordStrength is not removed from the page... Not sure of the reason. But it does disappear on UI.
3. There are several tests in the same test file that leverages hard coded timeouts. And also it seems to be beyond the scope of this ticket.
4. Looks like it takes me more time to investigate and fix things in the direction of your opinions. Also, you seem to be OOF until next week or so (as seen from slack status).

Owing to all above reasons, I am merging this PR.
I think there can be another task for this improvement.

2023-08-08 05:52 UTC, merged